### PR TITLE
Create_labels_if_missing parameter for updating multiple column values

### PR DESCRIPTION
**Pull request by andrewrgoss**
Allow create_labels_if_missing parameter (for dropdown column type) to be passed when updating multiple column values

### CODE REVIEW

**Comment by chdastolfo** [comment]
@andrewrgoss Thanks for your contribution! I can take a look later this week.

**Review by chdastolfo — DISMISSED** [review]
@andrewrgoss LGTM - would you mind bumping the version number to 1.3.0? I'll merge and deploy after.

**Comment by andrewrgoss** [comment]
@chdastolfo version bumped to 1.3.0.

**Review by chdastolfo — APPROVED** [review]
👍 LGTM

**Comment by andrewrgoss** [comment]
Looks like one more approval is needed to merge. @rhymiz?

**Review by rhymiz — APPROVED** [review]

**Comment by rhymiz** [comment]
@chdastolfo @andrewrgoss sorry for the delay -- all set to merge and cut a new version

**Pull request merged**
