### PR TITLE
Added Notification Resource to the package.

### PR DESCRIPTION
**Pull request by shaurya-blip**
# Hello!
I am SblipDev and I have added notification resource in the monday package.  My contribution will now let us 

* Create notifications

#### Notifications Resource (monday.notifications)
- `create_notification(user_id, target_id, text, target_type)` - The create_notification mutation allows to trigger a notification within the platform (will also send out an email if the recipient's email preferences are set up accordingly). 

I hope you like it. Have a nice day! 
I have also written unit tests for this.

### CODE REVIEW

**Review by rhymiz — APPROVED** [review]
Thanks for your contribution. Pending @chdastolfo's review, we should be good to include this work in the next version of the library.

**Comment by shaurya-blip** [comment]
Any updates?

**Comment by chdastolfo** [comment]
I can take a look today.

**Comment by chdastolfo** [comment]
@shaurya-blip This looks good. Could you please update the patch version number in `__version__.py `? Once you've done that a new version should automatically deploy to PyPi on merge if all of the checks pass.

**Comment by chdastolfo** [comment]
@rhymiz I think I was removed as collaborator on this repo - I can't add myself as reviewer or merge stuff.

**Review by chdastolfo — APPROVED** [review]
👍 Will have to update version number before drafting new release.

**Pull request merged**
