### PR TITLE
Parse board ids to integer type

### PR DESCRIPTION
**Pull request by iramluism**
when board_id is passed to get_board_items_query function parser ids to integer type

### CODE REVIEW

**Comment by rhymiz** [comment]
hey @iramluism , thanks for your contribution!

Do you mind adding more context in the description about what problems this PR addresses?

**Comment by chdastolfo** [comment]
@iramluism I'd second @rhymiz  request, and also ask that you add tests to check that logic and that the query is formed correctly when passed different input types. Thank you!

**Comment by rhymiz** [comment]
@iramluism just pinging you one last time before we close this PR because of inactivity 😄

**Comment by rhymiz** [comment]
@iramluism closing this pr. reason: no response.

**Pull request closed without merging**
