### PR TITLE
Added workspaces resource to the package.

### PR DESCRIPTION
**Pull request by shaurya-blip**
# Hello!
I am SblipDev and I have added workspace resource in the monday package.  My contribution will now let us 

* Create workspaces
* Add users to workspaces
* Delete users from workspaces
* Add teams to workspaces
* Delete teams from workspaces.

### Workspaces Resource (monday.workspaces)
- `get_workspaces()` - Get all workspaces.

- `create_workspace(name, kind, description)` - Create workspace with the given name, kind and description. 

- `add_users_to_workspace(workspace_id, [user_ids], kind)` - Add given users of the given kind to the given workspace.

- `delete_users_from_workspace(workspace_id, [user_ids])` - Delete given users from the given workspace.

- `add_teams_to_workspace(workspace_id, [team_ids])` - Add given teams to the given workspace.

- `delete_teams_from_workspace(workspace_id, [team_ids])` - Delete given teams from the given workspace.

I hope you like it. Have a nice day!

### CODE REVIEW

**Comment by rhymiz** [comment]
hey @shaurya-blip thanks for your contribution! We'll take a look and get this merged in.

@chdastolfo do you mind reviewing this PR?

**Comment by chdastolfo** [comment]
@rhymiz @shaurya-blip Yep, I'll take a look this week!

**Review by chdastolfo — CHANGES_REQUESTED** [review]
Hi @shaurya-blip - this looks good, but please add some unit tests for the new WorkspaceResource. Once those are in there and look good, this can be merged.

**Comment by shaurya-blip** [comment]
Hi @chdastolfo, I had recently deleted the forked version of your repo because I thought that you were inactive or something. So, I have made a new PR with the changes you have requested. Really sorry for this inconvenience. Thank you. 

Here is the new PR -> [https://github.com/ProdPerfect/monday/pull/48](https://github.com/ProdPerfect/monday/pull/48)

Again, sorry for the inconvenience.

**Pull request closed without merging**
